pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          serviceAccountName: jenkins-deployer
          containers:
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock    
        '''
    }
  }
  stages {
 
   stage('Build Java project - demo-app') {
     steps{
       container('docker') {
         script {
           sh 'cd ci-cd;./build.sh'
         }
       }
     }
   }

   stage('Build demo-app tomcat image') {
     steps{
       container('docker') {
         script {
           sh 'cd ci-cd/docker;./make-image.sh'
         }
       }
     }
   }

   stage('Pushing demo-app tomcat Image') {
     environment {
       registryCredential = 'Dockerhub-credentials'
     }
     steps{
       container('docker') {
         script {
           withDockerRegistry([ credentialsId: 'Dockerhub-credentials', url: '' ]) {
             sh 'cd ci-cd/docker;./push-image-to-docker-registry.sh'
           }
         }
       }
     }
   }

 }
}
